### ISSUE TITLE
extract torrent ggpk

### ISSUE THREAD

**Issue by Chuanhsing** [aianlinb/LibGGPK2#14]
System.OverflowException: Arithmetic operation resulted in an overflow.
   at LibBundle.BundleContainer.Read(BinaryReader br) in D:\GitHub\LibGGPK2\LibBundle\BundleContainer.cs:line 109
   at LibGGPK2.GGPKContainer.Export(IEnumerable`1 list, Action ProgressStep) in D:\GitHub\LibGGPK2\LibGGPK2\GGPKContainer.cs:line 211
   at VisualGGPK2.MainWindow.<>c__DisplayClass23_0.<OnExportClicked>b__0() in D:\GitHub\LibGGPK2\VisualGGPK2\MainWindow.xaml.cs:line 450

libggpk2 should skip missing files and extract available files.

**Comment by aianlinb** [comment]
Fixed in v0.11.4

**Comment by alcor75** [comment]
With version v0.11.4 i get this error if i try to view any .dat file:

 System.NullReferenceException: Object reference not set to an instance of an object.
at LibGGPH2.Records.BundleFileNode.ReadContent(StreamggpkStream) in
c:\Bot\GGPKVievers\LibGGPK2-master\LibGGPK2\BundleFileNode.cs:line 59
at VisualGGPK2.MainWindow.OnTreeSelectedChanged(Object sender, RoutedPropertyChangedEventArgs`1 e) in
c:\Bot\GGPKVievers\LibGGPK2-master\VisualGGPK2\MainWindow.xaml.cs:line 238

I'm i doing something wrong?

Tnx you.

**Comment by aianlinb** [comment]
@alcor75 That’s because the torrent GGPK file does not contain the dat files

**Comment by alcor75** [comment]
Ah! shame on me.
Tnx for the fast answer.

**Comment by zaafar** [comment]
Just an FYI: After the patch, looks like Chests got some new data.
![image](https://user-images.githubusercontent.com/5079646/126817962-2786d638-6f87-4691-8508-2359e7beb555.png)

**Comment by aianlinb** [comment]
@zaafar Fixed in v0.12.0
