### ISSUE TITLE
大大你好，v0.12.4在編輯.dat檔案后保存時彈出ErrorWidow報錯下面是報錯的Text

### ISSUE THREAD

**Issue by Acer-bdog** [aianlinb/LibGGPK2#17]
大大你好，v0.12.4在編輯.dat檔案后保存時彈出ErrorWidow報錯下面是報錯的Text,我編輯的是Words.dat這個檔案，他的物品名字在VisualGGPK2程式裏是Text和Text2的項目裏，不管是那個Text編輯后按Save保存都會彈出下面的錯誤，我還有編輯BaseItemTypes.dat這個檔，它的物品名字是在Name項目裏，所以編輯後保存就可以正常地保存，不會彈出窗體報錯。
謝謝大大。

System.NullReferenceException: Object reference not set to an instance of an object.
   at LibDat2.DatContainer.WriteType(BinaryWriter writer, Object o, Int64& pointer, String type) in C:\LibGGPK2\LibDat2\DatContainer.cs:line 636
   at LibDat2.DatContainer.Save(Stream stream, Boolean x64, Boolean UTF32) in C:\LibGGPK2\LibDat2\DatContainer.cs:line 526
   at LibDat2.DatContainer.Save(Boolean x64, Boolean UTF32) in C:\LibGGPK2\LibDat2\DatContainer.cs:line 504
   at VisualGGPK2.MainWindow.OnSaveDatClicked(Object sender, RoutedEventArgs e) in C:\LibGGPK2\VisualGGPK2\MainWindow_Dat.cs:line 257
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Acer-bdog** [comment]
Words.dat按下Save保存彈出報錯
> 
![image](https://user-images.githubusercontent.com/71896863/127811853-1dd2d2e2-58a3-40da-aefd-7f39e882177a.png)


BaseItemTypes.dat可以正常地按下Save保存
> 
![image](https://user-images.githubusercontent.com/71896863/127811568-47573ffa-1c41-4463-aa62-45e4a72aac02.png)
