### ISSUE TITLE
bug reporting

### ISSUE THREAD

**Issue by Lei-ciccc** [aianlinb/LibGGPK2#2]
When reading the content.ggpk file, an ErrorWindow appeared, saying the followings. 
Can't figure out the solution, so I wonder if the author may help me with this.
ps: The first time I use LibGGPK2 several days ago it sucessed, and I exchanged some files also sucessed without crashing the game.
_________________________________________________________________________________________________________________
System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGGPK2.GGPKContainer..ctor(String path, Boolean BundleMode) in C:\LibGGPK2\LibGGPK2\GGPKContainer.cs:line 56
   at VisualGGPK2.MainWindow.OnLoaded(Object sender, RoutedEventArgs e) in C:\LibGGPK2\VisualGGPK2\MainWindow.xaml.cs:line 71
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by aianlinb** [comment]
Seems that the FreeRecordList of your GGPK is broken.
This may happended if you have modified GGPK with old version libggpk.
Try open the GGPK with this to fix it:
[FixFreeRecords.zip](https://github.com/aianlinb/LibGGPK2/files/5648228/FixFreeRecords.zip)
If still not work, then redownload the GGPK.

**Comment by Lei-ciccc** [comment]
Thanks a lot. Yesterday I used the backup GGPK and experienced the following:

- First I replaced the “broken” GGPK file with backup file, and found the backup could be open. But after being modified only once, the file could not be opened anymore (game still working well).

- However, after replacing this second “broken” GGPK file with the backup file and try again, I found everything go on well. This time the file could be opened and modified just like it should be, at any time. But I have done nothing different from the paragraph above. I used the Pre-Release v0.5.0 all the time. 

- Seems that the error happens randomly. I will keep the FixFreeRecords file and try it if error happens again.

ps: Cheer for the v0.6.0 releasing, and thank you very much.

**Comment by aianlinb** [comment]
Fixed https://github.com/aianlinb/LibGGPK2/commit/db1a6c71549264333125257664ba7a11c0dde1b6

**Comment by voguelike** [comment]
yesterday, i ran into this issue again before you deployed today's fix. i tried using fixfreerecords to fix it but it crashes halfway through due to "invalid tag" as seen here:
![invalid tag](https://user-images.githubusercontent.com/73729626/101996245-8b082c00-3c9e-11eb-9886-7fff5bf76e70.png)

thankfully my game isn't crashing so far so i'm just unable to do any additional changes and hopefully it stays like that until you can look into this.

anyways, thank you for so much for working on this tool, and for fixing this original issue! hopefully this won't be able to happen again now.

**Comment by aianlinb** [comment]
@voguelike I think you may have to redownload the whole GGPK.
