### ISSUE TITLE
Errors on CraftingBench* dats 

### ISSUE THREAD

**Issue by dotnetdan** [aianlinb/LibGGPK2#21]
Hi,

I noticed the following files can't be viewed:

- CraftingBenchOptions.dat
- CraftingBenchSortCategories.dat

The error is 

```
---------------------------
Error
---------------------------
System.Exception: CraftingBenchOptions.dat : Actual record length: 191 is not equal to that defined in DatDefinitions: 175

   at LibDat2.DatContainer..ctor(Stream stream, String fileName) in C:\LibGGPK2\LibDat2\DatContainer.cs:line 91

   at VisualGGPK2.MainWindow.OnTreeSelectedChanged(Object sender, RoutedPropertyChangedEventArgs`1 e) in C:\LibGGPK2\VisualGGPK2\MainWindow.xaml.cs:line 300
---------------------------
OK   
---------------------------
```

**Comment by aianlinb** [comment]
Fixed
Replace your DatDefinitions.json with the lastest one
https://github.com/aianlinb/LibGGPK2/blob/master/LibDat2/DatDefinitions.json
