### ISSUE TITLE
GGPK工具打开选中Content.ggpk报错

### ISSUE THREAD

**Issue by 13548506407** [aianlinb/LibGGPK2#33]
System.DllNotFoundException: Unable to load DLL 'oo2core_9_win64.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
at LibBundle.BundleContainer.OodleLZ_Decompress(Byte[] buffer, Int32 bufferSize, Byte[] result, Int64 outputBufferSize, Int32 a, Int32 b, Int32 c, IntPtr d, Int64 e, IntPtr f, IntPtr g, IntPtr h, Int64 i, Int32 ThreadModule)
at LibBundle.BundleContainer.Read(BinaryReader br) in C:\LibGGPK2\LibBundle\BundleContainer.cs:line 115
at LibBundle.IndexContainer..ctor(BinaryReader br) in C:\LibGGPK2\LibBundle\IndexContainer.cs:line 27
at LibGGPK2.GGPKContainer..ctor(String path, Boolean BundleMode, Boolean SteamMode, Boolean BuildTree) in C:\LibGGPK2\LibGGPK2\GGPKContainer.cs:line 92
at VisualGGPK2.MainWindow.<OnLoaded>b__13_0() in C:\LibGGPK2\VisualGGPK2\MainWindow.xaml.cs:line 134
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
at VisualGGPK2.MainWindow.OnLoaded(Object sender, RoutedEventArgs e) in C:\LibGGPK2\VisualGGPK2\MainWindow.xaml.cs:line 134
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

我下载的最新的版本

**Comment by 13548506407** [comment]
用GGPK工具打开Content.ggpk出现的

**Comment by aianlinb** [comment]
@13548506407 你需要 oo2core_9_win64.dll
![image](https://user-images.githubusercontent.com/29705994/165043245-b6f0acc3-49e1-4b54-b294-ea0424ceecbb.png)

**Comment by 13548506407** [comment]
我看到下载的GGPK工具文件夹里面有这个文件呀，但是工具打开的时候为什么找不到呢

**Comment by 13548506407** [comment]
![image](https://user-images.githubusercontent.com/29673564/165045104-f5fd0e07-f04a-4714-8634-a09dc93bfe1a.png)
这个模块在这里，为什么会找不到此模块呢，是不是这个启动程序有问题呢
