### ISSUE TITLE
大佬，这是不是启动程序的问题

### ISSUE THREAD

**Issue by 13548506407** [aianlinb/LibGGPK2#34]
![image](https://user-images.githubusercontent.com/29673564/165049399-f6f49904-e413-4234-9fcc-1a2885588c46.png)
System.DllNotFoundException: Unable to load DLL 'oo2core_9_win64.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
at LibBundle.BundleContainer.OodleLZ_Decompress(Byte[] buffer, Int32 bufferSize, Byte[] result, Int64 outputBufferSize, Int32 a, Int32 b, Int32 c, IntPtr d, Int64 e, IntPtr f, IntPtr g, IntPtr h, Int64 i, Int32 ThreadModule)
at LibBundle.BundleContainer.Read(BinaryReader br) in C:\LibGGPK2\LibBundle\BundleContainer.cs:line 115
at LibBundle.IndexContainer..ctor(BinaryReader br) in C:\LibGGPK2\LibBundle\IndexContainer.cs:line 27
at LibGGPK2.GGPKContainer..ctor(String path, Boolean BundleMode, Boolean SteamMode, Boolean BuildTree) in C:\LibGGPK2\LibGGPK2\GGPKContainer.cs:line 92
at VisualGGPK2.MainWindow.b__13_0() in C:\LibGGPK2\VisualGGPK2\MainWindow.xaml.cs:line 134
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
at VisualGGPK2.MainWindow.OnLoaded(Object sender, RoutedEventArgs e) in C:\LibGGPK2\VisualGGPK2\MainWindow.xaml.cs:line 134
at System.Threading.Tasks.Task.<>c.b__128_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 13548506407** [comment]
我不是没有这个文件，这文件我有啊，还是说我的 .net环境装的有问题

**Comment by 13548506407** [comment]
完全按照B站视频操作，就是程序有问题啊

**Comment by aianlinb** [comment]
@13548506407 你可能沒有安裝 Visual C++ Redistributable

**Comment by 13548506407** [comment]
感谢大佬，确实是少了这个程序，现在可以加载了
